import pandas as pd
import pandas_ta as ta  # noqa: F401
import plotly.graph_objects as go

from frontend.visualization import theme


def get_bbands_traces(df, bb_length, bb_std):
    tech_colors = theme.get_color_scheme()
    df.ta.bbands(length=bb_length, lower_std=bb_std, upper_std=bb_std, append=True)
    
    # Dynamically find the actual column names generated by pandas-ta
    # This handles both integer (BBU_100_2_2) and float (BBU_100_2.0_2.0) formats
    bb_cols = [col for col in df.columns if col.startswith('BB')]
    bb_upper = next((col for col in bb_cols if col.startswith('BBU_')), None)
    bb_middle = next((col for col in bb_cols if col.startswith('BBM_')), None)
    bb_lower = next((col for col in bb_cols if col.startswith('BBL_')), None)
    
    if not all([bb_upper, bb_middle, bb_lower]):
        raise ValueError(f"Bollinger Bands columns not found. Available columns: {bb_cols}")
    
    traces = [
        go.Scatter(x=df.index, y=df[bb_upper], line=dict(color=tech_colors['upper_band']),
                   name='Upper Band'),
        go.Scatter(x=df.index, y=df[bb_middle], line=dict(color=tech_colors['middle_band']),
                   name='Middle Band'),
        go.Scatter(x=df.index, y=df[bb_lower], line=dict(color=tech_colors['lower_band']),
                   name='Lower Band'),
    ]
    return traces


def get_volume_trace(df):
    df.index = pd.to_datetime(df.timestamp, unit='s')
    return go.Bar(x=df.index, y=df['volume'], name="Volume", marker_color=theme.get_color_scheme()["volume"],
                  opacity=0.7)


def get_macd_traces(df, macd_fast, macd_slow, macd_signal):
    tech_colors = theme.get_color_scheme()
    df.ta.macd(fast=macd_fast, slow=macd_slow, signal=macd_signal, append=True)
    
    # Dynamically find MACD column names
    macd_cols = [col for col in df.columns if 'MACD' in col]
    macd = next((col for col in macd_cols if col.startswith('MACD_')), None)
    macd_s = next((col for col in macd_cols if col.startswith('MACDs_')), None)
    macd_hist = next((col for col in macd_cols if col.startswith('MACDh_')), None)
    
    if not all([macd, macd_s, macd_hist]):
        raise ValueError(f"MACD columns not found. Available columns: {macd_cols}")
    
    traces = [
        go.Scatter(x=df.index, y=df[macd], line=dict(color=tech_colors['macd_line']),
                   name='MACD Line'),
        go.Scatter(x=df.index, y=df[macd_s], line=dict(color=tech_colors['macd_signal']),
                   name='MACD Signal'),
        go.Bar(x=df.index, y=df[macd_hist], name='MACD Histogram')
    ]
    return traces


def get_supertrend_traces(df, length, multiplier):
    tech_colors = theme.get_color_scheme()
    df.ta.supertrend(length=length, multiplier=multiplier, append=True)
    
    # Dynamically find SuperTrend column names
    st_cols = [col for col in df.columns if 'SUPERT' in col]
    supertrend_d = next((col for col in st_cols if col.startswith('SUPERTd_')), None)
    supertrend = next((col for col in st_cols if col.startswith('SUPERT_') and not col.startswith('SUPERTd_')), None)
    
    if not all([supertrend, supertrend_d]):
        raise ValueError(f"SuperTrend columns not found. Available columns: {st_cols}")
    
    df = df[df[supertrend] > 0]

    # Create segments for line with different colors
    segments = []
    current_segment = {"x": [], "y": [], "color": None}

    for i in range(len(df)):
        if i == 0 or df[supertrend_d].iloc[i] == df[supertrend_d].iloc[i - 1]:
            current_segment["x"].append(df.index[i])
            current_segment["y"].append(df[supertrend].iloc[i])
            current_segment["color"] = tech_colors['buy'] if df[supertrend_d].iloc[i] == 1 else tech_colors['sell']
        else:
            segments.append(current_segment)
            current_segment = {"x": [df.index[i - 1], df.index[i]],
                               "y": [df[supertrend].iloc[i - 1], df[supertrend].iloc[i]],
                               "color": tech_colors['buy'] if df[supertrend_d].iloc[i] == 1 else tech_colors['sell']}

    segments.append(current_segment)

    # Create traces from segments
    traces = [
        go.Scatter(
            x=segment["x"],
            y=segment["y"],
            mode='lines',
            line=dict(color=segment["color"], width=2),
            name='SuperTrend'
        ) for segment in segments
    ]

    return traces
